/**
 * Fabulator API
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Json'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Json'));
  } else {
    // Browser globals (root is window)
    if (!root.FabulatorApi) {
      root.FabulatorApi = {};
    }
    root.FabulatorApi.Model5 = factory(root.FabulatorApi.ApiClient, root.FabulatorApi.Json);
  }
}(this, function(ApiClient, Json) {
  'use strict';




  /**
   * The Model5 model module.
   * @module model/Model5
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Model5</code>.
   * @alias module:model/Model5
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Model5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Model5} obj Optional instance to populate.
   * @return {module:model/Model5} The populated <code>Model5</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = Json.constructFromObject(data['data']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Json} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


