/**
 * Fabulator API
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Json'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Json'));
  } else {
    // Browser globals (root is window)
    if (!root.FabulatorApi) {
      root.FabulatorApi = {};
    }
    root.FabulatorApi.Model14 = factory(root.FabulatorApi.ApiClient, root.FabulatorApi.Json);
  }
}(this, function(ApiClient, Json) {
  'use strict';




  /**
   * The Model14 model module.
   * @module model/Model14
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Model14</code>.
   * @alias module:model/Model14
   * @class
   * @param json {module:model/Json} 
   */
  var exports = function(json) {
    var _this = this;

    _this['json'] = json;
  };

  /**
   * Constructs a <code>Model14</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Model14} obj Optional instance to populate.
   * @return {module:model/Model14} The populated <code>Model14</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('json')) {
        obj['json'] = Json.constructFromObject(data['json']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Json} json
   */
  exports.prototype['json'] = undefined;



  return exports;
}));


