/**
 * Fabulator API
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Model6', 'model/Model9'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Model6'), require('../model/Model9'));
  } else {
    // Browser globals (root is window)
    if (!root.FabulatorApi) {
      root.FabulatorApi = {};
    }
    root.FabulatorApi.RuleApi = factory(root.FabulatorApi.ApiClient, root.FabulatorApi.Model6, root.FabulatorApi.Model9);
  }
}(this, function(ApiClient, Model6, Model9) {
  'use strict';

  /**
   * Rule service.
   * @module api/RuleApi
   * @version 1.0.0
   */

  /**
   * Constructs a new RuleApi. 
   * @alias module:api/RuleApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deleteRuleV1Id operation.
     * @callback module:api/RuleApi~deleteRuleV1IdCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/RuleApi~deleteRuleV1IdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.deleteRuleV1Id = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteRuleV1Id");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/rule/v1/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getRuleV1InfoId operation.
     * @callback module:api/RuleApi~getRuleV1InfoIdCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/RuleApi~getRuleV1InfoIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.getRuleV1InfoId = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getRuleV1InfoId");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/rule/v1/info/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the patchRuleV1UpdateIdFieldValue operation.
     * @callback module:api/RuleApi~patchRuleV1UpdateIdFieldValueCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {String} field 
     * @param {String} value 
     * @param {module:api/RuleApi~patchRuleV1UpdateIdFieldValueCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.patchRuleV1UpdateIdFieldValue = function(id, field, value, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling patchRuleV1UpdateIdFieldValue");
      }

      // verify the required parameter 'field' is set
      if (field === undefined || field === null) {
        throw new Error("Missing the required parameter 'field' when calling patchRuleV1UpdateIdFieldValue");
      }

      // verify the required parameter 'value' is set
      if (value === undefined || value === null) {
        throw new Error("Missing the required parameter 'value' when calling patchRuleV1UpdateIdFieldValue");
      }


      var pathParams = {
        'id': id,
        'field': field,
        'value': value
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/rule/v1/update/{id}/{field}/{value}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postRuleV1AddIddomain operation.
     * @callback module:api/RuleApi~postRuleV1AddIddomainCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} iddomain 
     * @param {Object} opts Optional parameters
     * @param {module:model/Model6} opts.body 
     * @param {module:api/RuleApi~postRuleV1AddIddomainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.postRuleV1AddIddomain = function(iddomain, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'iddomain' is set
      if (iddomain === undefined || iddomain === null) {
        throw new Error("Missing the required parameter 'iddomain' when calling postRuleV1AddIddomain");
      }


      var pathParams = {
        'iddomain': iddomain
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/rule/v1/add/{iddomain}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postRuleV1QueryIddomainSkipLimit operation.
     * @callback module:api/RuleApi~postRuleV1QueryIddomainSkipLimitCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} iddomain 
     * @param {Number} skip 
     * @param {Number} limit 
     * @param {Object} opts Optional parameters
     * @param {module:model/Model9} opts.body 
     * @param {module:api/RuleApi~postRuleV1QueryIddomainSkipLimitCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.postRuleV1QueryIddomainSkipLimit = function(iddomain, skip, limit, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'iddomain' is set
      if (iddomain === undefined || iddomain === null) {
        throw new Error("Missing the required parameter 'iddomain' when calling postRuleV1QueryIddomainSkipLimit");
      }

      // verify the required parameter 'skip' is set
      if (skip === undefined || skip === null) {
        throw new Error("Missing the required parameter 'skip' when calling postRuleV1QueryIddomainSkipLimit");
      }

      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling postRuleV1QueryIddomainSkipLimit");
      }


      var pathParams = {
        'iddomain': iddomain,
        'skip': skip,
        'limit': limit
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/rule/v1/query/{iddomain}/{skip}/{limit}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putRuleV1UpdateIddomainId operation.
     * @callback module:api/RuleApi~putRuleV1UpdateIddomainIdCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {String} iddomain 
     * @param {Object} opts Optional parameters
     * @param {module:model/Model6} opts.body 
     * @param {module:api/RuleApi~putRuleV1UpdateIddomainIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.putRuleV1UpdateIddomainId = function(id, iddomain, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling putRuleV1UpdateIddomainId");
      }

      // verify the required parameter 'iddomain' is set
      if (iddomain === undefined || iddomain === null) {
        throw new Error("Missing the required parameter 'iddomain' when calling putRuleV1UpdateIddomainId");
      }


      var pathParams = {
        'id': id,
        'iddomain': iddomain
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/rule/v1/update/{iddomain}/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
