/**
 * Fabulator API
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FabulatorApi);
  }
}(this, function(expect, FabulatorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FabulatorApi.ExampleApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExampleApi', function() {
    describe('deleteExampleV1IddomainId', function() {
      it('should call deleteExampleV1IddomainId successfully', function(done) {
        //uncomment below and update the code to test deleteExampleV1IddomainId
        //instance.deleteExampleV1IddomainId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getExampleV1InfoIddomainId', function() {
      it('should call getExampleV1InfoIddomainId successfully', function(done) {
        //uncomment below and update the code to test getExampleV1InfoIddomainId
        //instance.getExampleV1InfoIddomainId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchExampleV1UpdateIddomainIdFieldValue', function() {
      it('should call patchExampleV1UpdateIddomainIdFieldValue successfully', function(done) {
        //uncomment below and update the code to test patchExampleV1UpdateIddomainIdFieldValue
        //instance.patchExampleV1UpdateIddomainIdFieldValue(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postExampleV1AddIddomain', function() {
      it('should call postExampleV1AddIddomain successfully', function(done) {
        //uncomment below and update the code to test postExampleV1AddIddomain
        //instance.postExampleV1AddIddomain(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postExampleV1QueryIddomainSkipLimit', function() {
      it('should call postExampleV1QueryIddomainSkipLimit successfully', function(done) {
        //uncomment below and update the code to test postExampleV1QueryIddomainSkipLimit
        //instance.postExampleV1QueryIddomainSkipLimit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putExampleV1UpdateIddomainId', function() {
      it('should call putExampleV1UpdateIddomainId successfully', function(done) {
        //uncomment below and update the code to test putExampleV1UpdateIddomainId
        //instance.putExampleV1UpdateIddomainId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putExampleV1UpdateJsonIddomainId', function() {
      it('should call putExampleV1UpdateJsonIddomainId successfully', function(done) {
        //uncomment below and update the code to test putExampleV1UpdateJsonIddomainId
        //instance.putExampleV1UpdateJsonIddomainId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
