/**
 * Fabulator API
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FabulatorApi);
  }
}(this, function(expect, FabulatorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FabulatorApi.SentenceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SentenceApi', function() {
    describe('deleteSentenceV1IdruleId', function() {
      it('should call deleteSentenceV1IdruleId successfully', function(done) {
        //uncomment below and update the code to test deleteSentenceV1IdruleId
        //instance.deleteSentenceV1IdruleId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSentenceV1InfoIdruleId', function() {
      it('should call getSentenceV1InfoIdruleId successfully', function(done) {
        //uncomment below and update the code to test getSentenceV1InfoIdruleId
        //instance.getSentenceV1InfoIdruleId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postSentenceV1AddIdrule', function() {
      it('should call postSentenceV1AddIdrule successfully', function(done) {
        //uncomment below and update the code to test postSentenceV1AddIdrule
        //instance.postSentenceV1AddIdrule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putSentenceV1UpdateIdruleId', function() {
      it('should call putSentenceV1UpdateIdruleId successfully', function(done) {
        //uncomment below and update the code to test putSentenceV1UpdateIdruleId
        //instance.putSentenceV1UpdateIdruleId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
